### ISSUE TITLE
Handle Case Where Item is Deleted and Effects on Requests

### ISSUE THREAD

**Issue by ankitkayastha** [nesh170/asap-inventory-system#60]
Check out onDelete

**Comment by nesh170** [comment]
The issue is 

When an item gets deleted, the request automatically gets deleted :/

Currently it is set to ON_CASCADE:- when the item gets deleted, then the request automatically gets deleted. :/

Potential fix:-
Currently, we can use the on_delete=SET() method to route it to just change the function to cancel :D weeee

https://docs.djangoproject.com/en/dev/ref/models/fields/#django.db.SET

**Comment by nesh170** [comment]
https://github.com/nesh170/asap-inventory-system/pull/64
